screens/CardScreen.js

[FID-28]
[FID-28]: https://msc-etna.atlassian.net/browse/FID-28?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: creation de la page Cartes

---

.eslintrc.json
.expo/packager-info.json
.gitignore
App.js
app.json
babel.config.js
package-lock.json
package.json
reducers/username.js
screens/CardScreen.js
screens/HomeScreen.js
screens/LoginScreen.js
screens/MapScreen.js
screens/ProfilScreen.js
screens/ScanScreen.js

- *describe your work here ...*
- 
-
[FID-]

fix: esLint

---

.expo/packager-info.json
config/global.js
screens/ProfilScreen.js

- Connexion avec l'API central de FideCly
- Récupération de l'email de l'utilisateur 1
- Intégrer cette donnée dans le générateur de QR code afin de créer le QR code en fonction de l'email
[FID-53]
[FID-53]: https://msc-etna.atlassian.net/browse/FID-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: récupérer une donnée de l'API

---

.github/dependabot.yml

- remove reviewer from dependabot workflow to enable auto-merge
No JIRA ticket

fix: remove reviewer

---

screens/CardScreen.js
screens/MapScreen.js

- fixer le problème d'affichage et récupération des données via l'api
- 
-
[FID-27]
[FID-27]: https://msc-etna.atlassian.net/browse/FID-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat/fid 27/screen card wallet

---

App.js
src/components/Button.js
src/screens/LoginScreen.js

- Refactor de la page login selon la maquette figma
- 
-
[FID-147]
[FID-147]: https://msc-etna.atlassian.net/browse/FID-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: design de la page login

---

App.js
src/screens/RegisterScreen.js

- Page registerScreen CSS selon la maquette
- 
-
[FID-148]
[FID-148]: https://msc-etna.atlassian.net/browse/FID-148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor : design de la page registerScreen selon la maquette

---

src/screens/CardScreen.js

- Ajout de la barre de recherche
- Design des cartes comme la maquette
- Gérer l'affichage des images
- Mettre la condition si pas d'image afficher les initiales à la google
[FID-46]
[FID-46]: https://msc-etna.atlassian.net/browse/FID-46?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor:card selon maquette

---

src/screens/CardScreen.js

feat: searchbar logic

---

App.js
src/screens/ScanScreen.js

- Modification du fond
- Modification du texte plus percutant
- Ajout des bordures style objectif photo
[FID-164]
[FID-164]: https://msc-etna.atlassian.net/browse/FID-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor:design page scan

---

.expo/packager-info.json
App.js
src/screens/CardScreenInfo.js
src/screens/ProfilScreen.js
src/screens/ScanScreen.js

- Modification de la page profil selon maquette
- 
-
[FID-165]
[FID-165]: https://msc-etna.atlassian.net/browse/FID-165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: profil page design

---

App.js
src/components/Button.js
src/screens/EditProfilScreen.js
src/screens/ProfilScreen.js

- Création d'une nouvelle page EditProfilScreen.js afin de conserver cette fonctionnalité de LogOut
- Design de la page en fonction de la maquette
- Mise en place d'un formulaire en dur sans action possible
- Button "Se déconnecter" en place et à checker
[FID-166]
[FID-166]: https://msc-etna.atlassian.net/browse/FID-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat:ajout de la page editProfil

---

src/screens/NewsScreen.js

- NewsScreen init
- CSS et données fictives
-
[FID-10]
[FID-10]: https://msc-etna.atlassian.net/browse/FID-10?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat/fid 10/init news screen

---

src/screens/MapScreen.js

- Ajout d'une fonction qui gère la traduction
- 
-
[FID-176]
[FID-176]: https://msc-etna.atlassian.net/browse/FID-176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: traduction FR

---

src/screens/MapScreen.js

- l'utilisateur refuse la carte, on affiche quand meme la carte
- Centre de Paris
- getAllShop et pas en fonction de la position et du rayon
- Affiche tous les shop de la base sur la carte
[FID-133]
[FID-133]: https://msc-etna.atlassian.net/browse/FID-133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: refuse localisation

---

src/screens/MapScreen.js

- définition d'un max width pour éviter tout débordement
- Retirer cityzip et city pour éviter les doublons
- Ajout d'une fonction pour découper l'adresse et dissocier zip code et city de l'adresse
[FID-198]
[FID-198]: https://msc-etna.atlassian.net/browse/FID-198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: adresse trop longue

---

src/screens/CardScreenInfo.js
src/screens/InfoShopToAddScreen.js

- changement libellé pour un bouton sur InfoShopToAddScreen
- Ajout d'une section Historique 
- Logique à revoir 
[FID-205]
[FID-205]: https://msc-etna.atlassian.net/browse/FID-205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: card pour historique

---

src/screens/CardScreenInfo.js

fix bugs in cardscreeninfo page

fix bugs in cardscreeninfo page

---

src/screens/CardScreenInfo.js
src/screens/InfoShopToAddScreen.js
src/screens/MapScreen.js
src/screens/NewsScreen.js

- Page Newscreen : Affichage de 3 promotions par section de façon aléatoire
- Page Newscreen : Inclure les boutons pour générer des nouvelles promotions seulement dans la section souhaitée
- Autres pages : Uniformiser les card afin qu'elle se ressemble, ajout d'un border pour distinguer la carte
[FID-213]
[FID-213]: https://msc-etna.atlassian.net/browse/FID-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix:newscreen page

---

src/screens/InfoShopToAddScreen.js
src/screens/NewsScreen.js

- Page infoShopToAddScreen : mise en forme de la date à droite 
- Page NewsScreen, fix padding
[FID-211]
[FID-211]: https://msc-etna.atlassian.net/browse/FID-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: card css

---

src/screens/CardScreenInfo.js
src/screens/NewsScreen.js

fix newsscreen info page
